### ISSUE TITLE
Placeholders not working on /info

### ISSUE THREAD

**Issue by SnowBlitzz** [NucleusPowered/Gluon#2]
I can’t seem to get any placeholders to work on the /info text files. They just become blank. The placeholders work on every other plugins so it’s not the placeholder’s issue. @dualspiral

And yes I’m using the correct format {%placeholder%}

Tested on:
Sponge version 2800 and 2833
Nucleus latest 1.2.2
Gluon 1.0.3
PlaceholderAPI 4.4

**Comment by dualspiral** [comment]
[gluon-1.0.4.zip](https://github.com/NucleusPowered/Gluon/files/1649271/gluon-1.0.4.zip)

Try this version. I suspect it wasn't registering properly.

**Comment by SnowBlitzz** [comment]
Ok this one works

**Comment by SnowBlitzz** [comment]
Oops sorry for raising a false alarm.

It apparently only works on some placeholders that are not from the PlaceholderAPI itself. The placeholders from the PlaceholderAPI itself always give a blank in the /info files, even though /papi parse <player> <placeholder> gives the correct value.

**Comment by dualspiral** [comment]
Yep, I've just worked through it, it's actually a problem with Placeholder API itself, having just worked through it. Placeholder API Commands seem to bypass the normal parse method, hence they work. For Nucleus, which uses the parse method, [this line](https://github.com/rojo8399/PlaceholderAPI/blob/master/src/main/java/me/rojo8399/placeholderapi/impl/PlaceholderServiceImpl.java#L174) sends an empty optional to the Player expansion which rejects it - it thinks it's _only_ a relational parameter when it's both, so it fails at https://github.com/rojo8399/PlaceholderAPI/blob/master/src/main/java/me/rojo8399/placeholderapi/impl/placeholder/Defaults.java#L817.

This is not a Gluon problem, this is a Placeholder API problem.
